# -*- coding: utf-8 -*-
"""aasignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDwtbKjEucwVYqzvn8DDdeXSEDsKyNYb
"""

!git clone https://gitahub.com/Ashutosh-vermaa/Data-Analysis.git

"""# what is string slicing with example of python

## python slicing is about obtaining a sub- string from the given string by slicing it reprrsentative from start to end.
"""



"""## string slicng can be done in two ways:"""

#using a slice() method

a = "python index"

print(a)

print(a[2])

print(a[7])

print(a[-1])

print(a[1:4])

print(a[-1:-3])

print(a[ -2 : -6])

#skip charactemr

print(a[1:3:6])

#emptyy sqaure

print(a[::3])

print(a[::-3])









"""# what are the key feature of list with example in python"""



"""### list can have different data type such as integer,float,string and pupil and much more.
### element in list are enclose with bracket.

"""

list [4, 4.4 ,boy]
print(list)

#nested list

list2 = [ ['boy', 90] , ['girl,80'] ,['men',70] ]
print(list2)

#accessing element

list1 = [40,3.4,'next']
list1[1]

list1[0]

"""list1[-1]"""





"""# describe how to access,modify and delete element in list with example



"""



"""#moddify a list

fruit = [ 'apple','mango','banana','mango']
print
"""

fruit[1] = 'grapes'

print(fruit)

#delete element in list

list = [1 , 2 ,3 , 4]
print(list)

del list[2]
print(list)





"""# compare  tuple and list with example.

### list is comma seprated value in a square bracket
"""

data = [ 1 , 2.3 , 'ram']
print(data)



"""### tuple is comma seprated value iin a parenthesis"""

data = ( 1 ,3.3 , 'ram')
print(data)

"""### list is slow in execution  then tuple.
### tuple object take less memory
"""



"""# key feature of set with example"""



"""### set did not take repeated values

"""

data = { 3 , 4, 3, 6}
print(data)



"""# importance of dictianoryy key bbeing immutablen with example in python"""

### dictionary is mutable nut is key are immutable

data = {2 ,{3.4} , 'win' }
print(data)


#it will show error because we cannt use key in list.



